import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '@repo/ui/globals.css';
import { Providers } from '../providers';
import { ChatProvider } from '../context/ChatContext';
import { ThemeToggle } from '@repo/ui/components/ThemeToggle';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <Providers>
                    <div className="fixed top-4 right-4 z-50">
                        <ThemeToggle />
                    </div>
                    <ChatProvider>{children}</ChatProvider>
                </Providers>
            </body>
        </html>
    );
}
